export const ADD_RESERVATION = "ADD_RESERVATION";
export const RETRIEVE_RESERVATIONS = "RETRIEVE_RESERVATIONS";
export const UPDATE_RESERVATION = "UPDATE_RESERVATION";
export const DELETE_RESERVATION = "DELETE_RESERVATION";
